# Generated by Django 4.1.4 on 2023-02-13 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('chapter_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FootballPitch',
            fields=[
                ('pitch_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('sport_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FootballTeam',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('group', models.IntegerField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='FootballTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('played', models.IntegerField()),
                ('won', models.IntegerField()),
                ('drawn', models.IntegerField()),
                ('lost', models.IntegerField()),
                ('goals_for', models.IntegerField()),
                ('goals_against', models.IntegerField()),
                ('goal_difference', models.IntegerField()),
                ('points', models.IntegerField()),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.footballteam')),
            ],
        ),
        migrations.CreateModel(
            name='FootballSchedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_score', models.IntegerField(null=True)),
                ('opponent_score', models.IntegerField(null=True)),
                ('played', models.BooleanField(default=False)),
                ('team_penalty', models.IntegerField(null=True)),
                ('opponent_penalty', models.IntegerField(null=True)),
                ('time', models.TimeField()),
                ('opponent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opponent', to='home.footballteam')),
                ('pitch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.footballpitch')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='home.footballteam')),
            ],
        ),
    ]
