# Generated by Django 4.1.4 on 2023-02-17 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_chapter_chapter_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footballschedule',
            name='opponent_penalty',
        ),
        migrations.RemoveField(
            model_name='footballschedule',
            name='team_penalty',
        ),
        migrations.AddField(
            model_name='chapter',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='footballpitch',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='footballschedule',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='footballtable',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='footballteam',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sport',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FootballKnockout',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('team_score', models.IntegerField(null=True)),
                ('opponent_score', models.IntegerField(null=True)),
                ('played', models.BooleanField(default=False)),
                ('team_penalty', models.IntegerField(null=True)),
                ('opponent_penalty', models.IntegerField(null=True)),
                ('time', models.TimeField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('opponent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opponent_id', to='home.footballteam')),
                ('pitch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.footballpitch')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.footballteam')),
            ],
        ),
    ]
