# Generated by Django 4.1.4 on 2023-02-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_footballschedule_opponent_penalty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballschedule',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
