# Generated by Django 4.1.4 on 2023-02-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_badmintonpitch_cricketpitch_kabaddipitch_khopitch_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="khoschedule",
            name="opponent_score",
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name="khoschedule",
            name="team_score",
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name="khotable",
            name="goal_difference",
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name="khotable",
            name="goals_against",
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name="khotable",
            name="goals_for",
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
    ]
