# Generated by Django 4.1.4 on 2023-02-18 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_footballschedule_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballschedule',
            name='pitch_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.footballpitch'),
        ),
    ]
