# Generated by Django 4.1.4 on 2023-02-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_alter_khoschedule_opponent_score_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="khoschedule",
            name="opponent_score",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="khoschedule",
            name="team_score",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="khotable",
            name="goal_difference",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="khotable",
            name="goals_against",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="khotable",
            name="goals_for",
            field=models.FloatField(null=True),
        ),
    ]
